In [1]:
from pyspark.sql import functions as sparkf

raw_df = spark.createDataFrame(
 [
  ('Store 1',1,448),
  ('Store 1',2,None),
  ('Store 1',3,499),
  ('Store 1',44,432),
  (None,None,None),
  ('Store 2',1,355),
  ('Store 2',1,355),
  ('Store 2',None,345),
  ('Store 2',3,387),
  ('Store 2',4,312)
],
 ['Store','WeekInMonth','Revenue']
)

In [2]:
raw_df.count()

10

In [3]:
raw_df.printSchema()

root
 |-- Store: string (nullable = true)
 |-- WeekInMonth: long (nullable = true)
 |-- Revenue: long (nullable = true)

In [4]:
raw_df.select(['Store']).show()

+-------+
|  Store|
+-------+
|Store 1|
|Store 1|
|Store 1|
|Store 1|
|   null|
|Store 2|
|Store 2|
|Store 2|
|Store 2|
|Store 2|
+-------+

In [5]:
raw_df.select([col for col in raw_df.columns]).show()

+-------+-----------+-------+
|  Store|WeekInMonth|Revenue|
+-------+-----------+-------+
|Store 1|          1|    448|
|Store 1|          2|   null|
|Store 1|          3|    499|
|Store 1|         44|    432|
|   null|       null|   null|
|Store 2|          1|    355|
|Store 2|          1|    355|
|Store 2|       null|    345|
|Store 2|          3|    387|
|Store 2|          4|    312|
+-------+-----------+-------+

In [6]:
raw_df.select([col for col in raw_df.columns if col.startswith('Rev')]).show()

+-------+
|Revenue|
+-------+
|    448|
|   null|
|    499|
|    432|
|   null|
|    355|
|    355|
|    345|
|    387|
|    312|
+-------+

In [7]:
raw_df.select([sparkf.count(col) for col in raw_df.columns if col.startswith('Rev')]).show()

+--------------+
|count(Revenue)|
+--------------+
|             8|
+--------------+

In [8]:
raw_df.select([sparkf.count(col) for col in raw_df.columns]).show()

+------------+------------------+--------------+
|count(Store)|count(WeekInMonth)|count(Revenue)|
+------------+------------------+--------------+
|           9|                 8|             8|
+------------+------------------+--------------+

In [9]:
raw_df.select([sparkf.count(sparkf.when(sparkf.col(col).isNull(),col)) for col in raw_df.columns]).show()

+-----------------------------------------------+-----------------------------------------------------------+---------------------------------------------------+
|count(CASE WHEN (Store IS NULL) THEN Store END)|count(CASE WHEN (WeekInMonth IS NULL) THEN WeekInMonth END)|count(CASE WHEN (Revenue IS NULL) THEN Revenue END)|
+-----------------------------------------------+-----------------------------------------------------------+---------------------------------------------------+
|                                              1|                                                          2|                                                  2|
+-----------------------------------------------+-----------------------------------------------------------+---------------------------------------------------+

In [10]:
raw_df.select([sparkf.count(sparkf.when(sparkf.col(col).isNull(),col)).alias(col) for col in raw_df.columns]).show()

+-----+-----------+-------+
|Store|WeekInMonth|Revenue|
+-----+-----------+-------+
|    1|          2|      2|
+-----+-----------+-------+